### ISSUE TITLE
Part 1, Notebook 1: Guidelines for variable names

### ISSUE THREAD

**Issue by pssachdeva** [dlab-berkeley/Python-Fundamentals-Revamp#2]
In the challenge on variable names, question two asks "What guidelines aren't being followed?". No guidelines are specified prior to this, only the rules for variable names (which is asked for in question 1). 

I would recommend moving this challenge to right after the following section (with the tips on variable names).

**Comment by tomvannuenen** [comment]
Moved the section down to after the Guidelines Tip.
