### ISSUE TITLE
Choose between NLP dataset or Health dataset in Notebook 6

### ISSUE THREAD

**Issue by tomvannuenen** [dlab-berkeley/Python-Fundamentals-Revamp#6]
There are 2 versions of notebook 6 in Part II of the workshop. The old one is the tweets NLP dataset that Emily and Pratik introduced; the new one is a health dataset. The NEW notebook still needs work to make use of all the Pandas skills participants have built up to this point. 

In the NEW notebook, I did split up the Health CSV dataset so we can still do the for-loop and slicing. 

The question is which dataset/skillset we want to use. I do think the Health dataset does make sense given everything that's come before, but it needs work in terms of the challenges and Pandas operations we want participants to engage in.

**Comment by pssachdeva** [comment]
I took a look at the new notebook and I think it looks pretty good. What skills or functions do you think it doesn't effectively cover?

**Comment by pssachdeva** [comment]
The main thing I can think of is capping off the workshop with some kind of visualization, in the sense that we have shown them how to produce a "deliverable". You could use that plot the motivate the usage of CHIS as a dataset. The main difference I see is the lack of regressions and statistical tests, which I am not too worried about. Part 4 in the original lesson was so long that we often didn't make it to those parts, anyway.

**Comment by tomvannuenen** [comment]
OK, maybe it's just my own NLP bias. It felt like that project had a bit more meat to it somehow. Haven't had time to really explore the data carefully, but I bet there are some other interesting (and more unexpected) correlations that could be teased out.

Good idea to end with plot, will add that.

**Comment by pssachdeva** [comment]
I think you're right that there are more interesting questions that can be immediately answered with that dataset. But I think for a Fundamentals course, it's ok to go with something a bit more basic. We can see how it goes during the pilot, and switch back to the NLP dataset if we feel like it hampers engagement.

**Comment by tomvannuenen** [comment]
Would there be a way to sensibly use the dummified variables of general health or poverty level in the visualization of correlations?
